[package]
name = "yolite"
version = "0.1.0"
description = "A lightweight YouTube Music client."
authors = ["Yolite"]
edition = "2024"

[lib]
name = "yolite_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { git = "https://github.com/tauri-apps/tauri", rev = "e19121427332c8a14165999251cce415707a62fc", features = [] }

[dependencies]
dirs = "6.0.0"
discord-rich-presence = "1.1.0"
reqwest = { version = "0.12.24", default-features = false, features = ["json", "gzip", "rustls-tls"] }
ring = "0.17.14"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
tauri = { git = "https://github.com/tauri-apps/tauri", rev = "e19121427332c8a14165999251cce415707a62fc", features = [] }
thiserror = "2.0.17"
tokio = { version = "1.47.1", features = ["sync"] }
